import os
import json
from typing import Generator
from backend.models import StockResearchJob
from backend.agent.runtime import AgentRuntime

def get_template_content() -> str:
    """Read root stock research template instructions markdown securely with fallback checking paths."""
    paths_to_check = [
        os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "prompts", "stock_research_template.md")),
        os.path.abspath(os.path.join(os.getcwd(), "prompts", "stock_research_template.md")),
        "/app/prompts/stock_research_template.md"
    ]
    for p in paths_to_check:
        if os.path.exists(p):
            try:
                with open(p, "r", encoding="utf-8") as f:
                    return f.read()
            except Exception:
                continue
    return "Stock Research System Instructions: Gather fundamental parameters for the target stock symbol."

def gather_stock_data(job_id: int, symbol: str, db) -> Generator[str, None, str]:
    """
    Phase 1 Core Orchestrator: Drives agentic web extraction filling out fundamental parameter templates.
    Yields live SSE JSON block strings and returns final compiled text block.
    """
    job = db.query(StockResearchJob).filter(StockResearchJob.id == job_id).first()
    if job:
        job.status = "gathering"
        db.commit()

    template_markdown = get_template_content()
    
    system_instruction = f"""You are an elite, fully autonomous Financial Research Agent.
Your sole mission is to gather deep, verified fundamental data for the stock symbol: {symbol}.

CRITICAL EXECUTION CONSTRAINTS:
1. You MUST use your available tools synergistically: first execute `search_web` to dynamically discover accurate documentation links, then execute `browse_page` via Playwright to scrape those absolute URLs to extract financial metrics (Q4 FY26 or latest available).
2. You MUST produce your final output adhering strictly to the structured sections provided in the template below.
3. Keep searching alternative sources if initial websites lack specific parameter details. Do not stop until all 7 sections are thoroughly answered.

### TARGET TEMPLATE SCHEMA:
{template_markdown}
"""

    runtime = AgentRuntime(job_id=job_id, db_session=db, system_prompt=system_instruction)
    
    prompt = f"Begin gathering complete parameters for stock symbol: {symbol}. Return the completed research report formatted precisely as shown in the template."
    
    final_compiled_data = ""
    for chunk in runtime.run_stream(prompt=prompt, max_iterations=10):
        yield chunk

    # Retrieve final consolidated thought log string generated by model
    final_compiled_data = runtime.messages[-1].get("content", "") if runtime.messages else ""
    
    if job:
        job.gathered_data = final_compiled_data
        job.status = "evaluating"
        db.commit()
        
    yield json.dumps({"type": "phase_switch", "content": "Phase 1 compilation finalized. Transitioning to Phase 2 checklist evaluation..."})
    return final_compiled_data
